config/routes.rb
Rails.application.routes.draw do
  resources :users

  get 'welcome/index'

  get 'signup' => "users#new"

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :email, format: { with: /\S+@\S+/ },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 7, allow_blank: true }
  validates :username, format: { with: /\A[A-Z0-9]+\z/i },
                     uniqueness: { case_sensitive: false }

  def gravatar_id
    Digest::MD5::hexdigest(email.downcase)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: "Thanks for signing up"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :root, alert: "Account successfully deleted"
  end

  private

  def user_params
    params.require(:user).
    permit(:name, :email, :password, :password_confirmation, :about, :username)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_link(path)
    request.path == path ? 'active' : ''
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def profile_image(user)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
    image_tag(url, alt: user.name)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar">
    <%= link_to "Home", welcome_index_path, class: "button #{active_link(welcome_index_path)}" %>
    <%= link_to "Meet the team", users_path, class: "button #{active_link(users_path)}" %>
    <%= link_to "Sign up", signup_path, class: "button #{active_link(signup_path)}" %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LVCWebsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>
  <%= render 'layouts/header' %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render "shared/errors", object: user %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <% if user.new_record? %>
  <%= f.submit "Create Account" %>
  <% else %>
  <%= f.submit "Update Account" %>
  <% end %>

<% end %>

app/views/users/edit.html.erb
<h1> Edit Account</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>London Vegan Coders Team </h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= profile_image(user) %>
      <%= link_to user.name, user %>
      created
      <%= time_ago_in_words(user.created_at) %> ago
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<section class="user">
  <%= profile_image(@user) %>
  <h1><%= @user.name %></h1>
  <h2> <%= @user.username %></h2>
  <h2><%= mail_to(@user.email) %></h2>
  <p><%= @user.about %></p>
  <div class="actions"><%= link_to "Edit Account", edit_user_path(@user),
    class: "button edit" %></div>
  <div class="actions"><%= link_to "Delete Account", @user, method: :delete, data: { confirm: "Permanently delete you account?" },
  class: "button delete" %></div>
</section>

app/views/welcome/index.html.erb
<section class="welcome">
  <div>
    <h1>Welcome London Vegan Coders</h1>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sed nisi condimentum
      enim elementum finibus ut a elit. Pellentesque dictum molestie nibh a cursus. Ut malesuada
      viverra imperdiet.
    </p>
  </div>
  <%= image_tag "carrots_placeholder.png" %>
</section>